name        : libevent
version     : 2.0.22
release     : 3
source      :
    - https://sourceforge.net/projects/levent/files/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz : 71c2c49f0adadacfdbe6332a372c38cf9c8b7895bb73dabeaa53cdcc1d4e1fa3
license     :
    - BSD-3-Clause
summary     : event notification library
description : |
    libevent provides a mechanism to execute a callback function when a specific event occurs on a file descriptor, after a timeout has been reached, due to signals, or due to regular timeouts.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
