name       : libevent
version    : 2.1.11
release    : 7
source     :
    - https://github.com/libevent/libevent/releases/download/release-2.1.11-stable/libevent-2.1.11-stable.tar.gz : a65bac6202ea8c5609fd5c7e480e6d25de467ea1917c08290c521752f147283d
license    :
    - BSD-3-Clause
component  : system.utils
summary    : event notification library
description: |
    libevent provides a mechanism to execute a callback function when a specific event occurs on a file descriptor, after a timeout has been reached, due to signals, or due to regular timeouts.
setup      : |
    %patch -p1 < $pkgfiles/0001-Warn-if-forked-from-the-event-loop-during-event_reinit.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
