name       : libevent
version    : 2.1.8
release    : 4
source     :
    - https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz : 965cc5a8bb46ce4199a47e9b2c9e1cae3b137e8356ffdad6d94d3b9069b71dc2
license    :
    - BSD-3-Clause
component  : system.utils
summary    : event notification library
description: |
    libevent provides a mechanism to execute a callback function when a specific event occurs on a file descriptor, after a timeout has been reached, due to signals, or due to regular timeouts.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
