name       : libevent
version    : 2.1.10
release    : 5
source     :
    - https://github.com/libevent/libevent/archive/release-2.1.10-stable.tar.gz : 52c9db0bc5b148f146192aa517db0762b2a5b3060ccc63b2c470982ec72b9a79
license    :
    - BSD-3-Clause
component  : system.utils
summary    : event notification library
description: |
    libevent provides a mechanism to execute a callback function when a specific event occurs on a file descriptor, after a timeout has been reached, due to signals, or due to regular timeouts.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
